<a href="https://colab.research.google.com/github/TheVijaySidd/PythonForDataScience/blob/main/pythonBasics18Sep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hey Vijay, Welcome back')

Hey Vijay, Welcome back


In [ ]:
print('Happy Birthday ')

Happy Birthday Dear Modi Ji


In [ ]:
print('''This is to verify multiple line code works
in python ''')

This is to verify multiple line code works
in python 


In [ ]:
help()



Welcome to Python 3.10's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the internet at https://docs.python.org/3.10/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> keywords

Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import    

This part is to check how the text block is displayed

In [ ]:
name= input('Enter your name')
print('Hi ' +name)

Enter your nameTreasa
Hi Treasa


In [ ]:
print(True==1)
print("1" == 1)
x = 55 / 11
print(x)

True
False
5.0


In [ ]:
x=0
if x > 2:
    x = x*2
if x > 4:
    x = 0
print(x)

0


In [ ]:
a = 1
b = 0
c = 1
if (a and b):
    print("Scaler is awesome")
elif (a and c):
    print("ML is fun")
if (a and b and c):
    print("Python is amazing")
if (a or b or c):
    print("I love DS")

ML is fun
I love DS


In [ ]:
a = 4
b = -5
if a > 0:
    if b < 0:
        a = a - 2
    elif a > 5:
        a = a - 4
    else:
        a = a + 3
else:
    b = b + 2

print(a)

2


In [ ]:
x = 2
if x==2:
    x = 3
x = 4
else:
    x = 5
print(x)

SyntaxError: ignored

In [ ]:
str1=str(input())
str2=str(input())
str3=str1+"$"+str2
print(str3)

Hello
World
Hello$World


In [ ]:
print(type(int(float(input()))))

2.2
<class 'int'>


In [ ]:
print(bool(False-1))
print(bool(True-3))
print(True+3)
print(-50%7)

True
True
4
6


In [ ]:
in1=int(input('Enter the input number greate than 9'))
if in1

In [ ]:
import numpy as np
x=np.random.randint(50,size=(3,4))
print(x.ndim)

2


In [ ]:
x= np.arange(1,5).reshape(2,2)
y=np.arange(11,15).reshape(2,2)
t=np.hstack((x,y))
print(t)

[[ 1  2 11 12]
 [ 3  4 13 14]]


In [ ]:
##Take an integer input from the user and print alternate numbers from from 1 to input.
##Input will be a positive number > 1. INPUT - 7
#OUTPUT - 1 3 5 7 INPUT - 4
#OUTPUT - 1 3

In [ ]:
num=int(input())
start=1
while(start<=num):
  print(start)
  start=start+2



7
1
3
5
7


In [ ]:
#Take an input from the user and print alternate numbers from from 1 to input.
#If number is > 1 -> Print as required.
#Else print "Number is smaller than 1!" INPUT - 7
#OUTPUT - 1 3 5 7 INPUT - -5
#OUTPUT - Number is smaller than 1!

In [ ]:
num=int(input())
start=1
while(start<=num):
  if(num>1):
    print(start)
    start=start+2
  else:
    print(num +"is smaller than 1")

-5


In [ ]:
c = 0
while c<=10:
    print(c)
    if c%2:
       c-=1
    else:
       c+=1


In [ ]:
n=int(input())
i=1
mul=0
while(n>mul):
    mul=4*i
    if(mul<=n):
      print(mul, end=' ')
    i+=1

9
4 8 

In [ ]:
n=int(input())
d=2
while d<=n:
  print(d,end=' ')
  d+=2



15
2 4 6 8 10 12 14 

In [ ]:
from re import X
n=int(input())
x=1
while x<=n:
  X=n%2
  if d==0:
    print(n,end=' ')
  d +=1

In [ ]:
a=int(input())
b=int(input())
p=a**b
while a<1000 and b<1000:
    print(p)

In [ ]:
myl=[2,3,7,5]
sl=[3,2,5,7]
sortedmyl=sorted(myl)
print(sortedmyl)
slsort=sl.sort()
print(slsort)
print(sortedmyl==slsort)

[2, 3, 5, 7]
None
False


In [ ]:
n= int(input())
su=0
for i in range(1,n+1):
  su=su+i
print(su)

11
66


In [ ]:
for a in range(10):
  if (a%3==0):
    pass
  print(a, end=" ")

0 1 2 3 4 5 6 7 8 9 

In [ ]:
x = 1
for i in range(x):
    x=x+1
    print(i, end= " ")

0 

In [ ]:
sn=1
for i in range(sn,17,3):
  print(i,end=',')
  if i == 16:
    print(end='')


1,4,7,10,13,16,

In [ ]:
A= int(input())
s=0
for i in range(1,11):
  s=A*i
  print(A,'*',i,'=',s)

In [ ]:
i=2
if i==2:
    i+=1
for j in range(i):
    pass
    break
    i+=1
print(i)

3


In [ ]:
n=8
while n>=0:
   n -= 2
   if n%2==0:
       continue
   print(n, end=" ")
else:
   print("Exec", end=" ")

Exec 

In [ ]:
import random
def my_func():
  emotions =["M","h","d"]
  return random.choice(emotions)

result=my_func()
print(result)

h


Question 1 -
Create a date printing function (print_date) -
Should take 4 arguments -> day, month, year and style Styling Logic -
style -> 0 -> d/m/y
style -> 1 -> m/d/y
style -> any other value -> Invalid Style default style is 0.

In [ ]:
def dateprint(day,month,year,sl):
  if sl==0:
    print(day,month,year, sep='/')
  elif sl==1:
    print(month,day,year, sep='/')
  else:
    print('invalid style')
print(dateprint(10,10,2023,1))

10/10/2023
None


In [ ]:
num = int(input())
while num > 1:
    num = num // 3
print(num)

89
1


In [ ]:
num = int(input())
val = 0
for i in range(2, num):
    val = val + i
if val > 10:
    print('Hello, this is Raj')
else:
    print('There is no one')

6
Hello, this is Raj


In [ ]:
def main():
    T=int(input())
    i=1
    while(i<=T):
        A=int(input())
        if(A==0):
            print(0)
        else:
            temp=0
            while(A!=0):
                temp2=0
                temp+=temp2
                A=A//10
            print(temp)
        i+=1

if __name__ == '__main__':
    main()

3
111
0


KeyboardInterrupt: ignored

In [ ]:
x = "global"
def foo():
    global x
    print(x, end=",")
    x = "local"
    print(x, end=",")

foo()
print(x, end="")

global,local,local

In [ ]:
def foo():
    x = "hello world"

foo()
print(x)

local


In [ ]:
x = 5

def foo(x):
    x = 4

foo(x)
print(x)

5


In [ ]:
def Interest(p,c,t=2,r=0.09):
  return p*t*r


<function Interest at 0x7d960a0abe20>


In [ ]:
def not_even(lst):
  res = []
  for ele in lst:
    if (ele% 2 == 1): lst.remove(ele)
  return res
not_even(elements)
elements=[24,32,13,15,19,44,52,7,9,2,51]

NameError: ignored

Given list of all runs by Virat, print runs made in odd matches (Even Indexes). runs = [62, 85, 74, 10, 12, 101, 122, 99, 81, 55]

In [ ]:
runs=[62, 85, 74, 10, 12, 101, 122, 99, 81, 55]
for i in range(len(runs),)

In [ ]:
word = "Scaler Data Science Course"
word_list = list(word)
print(word_list[7:19])
print(word_list[7:18])

['D', 'a', 't', 'a', ' ', 'S', 'c', 'i', 'e', 'n', 'c', 'e']
['D', 'a', 't', 'a', ' ', 'S', 'c', 'i', 'e', 'n', 'c']


In [ ]:
[1, 3, 4, 4, 3, 1, 2, 3, 2][:6:2]

[1, 4, 3]

matrix = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[0,10,11]
]
what is the sum of all the elements?

In [ ]:

matrix = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[0,10,11]
]
sum=0
for row in matrix:
  for e in row:
    sum+=e
print(sum)

66


In [ ]:
matrix = [
[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[0,10,11]
]
sum=0
for row in matrix:
  sum+=e
  print(sum)


11
22
33
44


In [ ]:
arr1=[1,2,3]
arr2=[6,5,4]
arr1.extend(arr2)
arr2.sort()
print(arr1,arr2)

[1, 2, 3, 6, 5, 4] [4, 5, 6]


In [ ]:
arr=[1, 3, 4, 4, 3, 1, 2, 3, 2][:3]
print(arr)

[1, 3, 4]


In [ ]:
numbers=[1,2,3,4,5,6,7]
even=[]
for i in numbers:
  if i%2==0:
    even.append(i)
print(even)

[2, 4, 6]


In [ ]:
numbers = [10, 20, 30, 40, 50]
total = 0
for i in len(numbers):         #blank, Here we want to go through each element of the numbers, i refers to those elements
  total = total + i

num_size = len(numbers)
avg = total/num_size
print(avg)

TypeError: ignored

In [ ]:
for i in range(-6, -10, -1):
     print(i, end =" ")

-6 -7 -8 -9 

In [ ]:
x = [1, 2]
y = [2, 3]

for i in x:
    for j in y:
        print(i, j, end= " ")

1 2 1 3 2 2 2 3 

In [ ]:
a = [25, 2, 3, 57, 38, 41]
def solution(a):

    result=0
    for i in (len[a]):
        result=a[i]
    print(len())



In [ ]:
def convert(t):
    return t*9/5 + 32

print(convert(20))

68.0


In [ ]:
x = 55
def hi():
  return x
x +=10
print(hi())

65


In [ ]:
mystr=input()
print(mystr.reverse)

vijar


AttributeError: ignored

In [ ]:

strs=input()
new
for i in strs(::-1):

  if strs==


In [ ]:
def generate_str(lst):
  s=""
  for i in lst:
    s+=chr(i)


In [ ]:
mystr="vijay"
for i in mystr[::-1]:
  print(i.lower(),end="")



yajiv

In [ ]:
class Solution:

    def solve(self, A):
        for i in A[::-1]:
            print(i.lower(),end="")


NameError: ignored

In [ ]:
s="hello"
print( s[: : -1] )

olleh


In [ ]:
word = "Scaler Academy"
n = len(word)
word1 = word.upper()
word2 = word.lower()

converted_word = ""

for i in range(n):
     if i % 2 == 0:
          converted_word += word2[i]
          print(converted_word)
     else:
          converted_word += word1[i]
          print(converted_word)


s
sC
sCa
sCaL
sCaLe
sCaLeR
sCaLeR 
sCaLeR A
sCaLeR Ac
sCaLeR AcA
sCaLeR AcAd
sCaLeR AcAdE
sCaLeR AcAdEm
sCaLeR AcAdEmY


In [ ]:
a = 'hello'
b = a
a = 'yello'

print(b)
print(a)

hello
yello


In [ ]:
players = ['Jadeja','Rahul','Rohit']
players[len(players):] = ['Dhoni', 'Virat']
print(players)

['Jadeja', 'Rahul', 'Rohit', 'Dhoni', 'Virat']


In [ ]:
words= ['goOd','mORNing','HOW','are','yoU','todAy']

def upper_char(words):
  output=[]
  for i in range(len(words)):
    if words[i][2].isupper() == True:
      output.append(words[i])
  return output
upper_char(words)

['goOd', 'mORNing', 'HOW', 'yoU']

In [ ]:
bbt = {'Sheldon': 1, 'Leonard': 2}
bbt.update({'Penny': 2})
print(bbt)

{'Sheldon': 1, 'Leonard': 2, 'Penny': 2}


In [ ]:
freshers = {
    'student1': {'name': 'yash', 'salary': 7500},
    'student2': {'name': 'heet', 'salary': 8000},
    'student3': {'name':'smit', 'salary': 6500}
}
freshers['student3']['salary'] = 8500
print(freshers)

{'student1': {'name': 'yash', 'salary': 7500}, 'student2': {'name': 'heet', 'salary': 8000}, 'student3': {'name': 'smit', 'salary': 8500}}


In [ ]:
dict1 = {'age': 35, 'name': 'abc', 'salary': 45000}

val = dict1['age']

if val in dict1:
    print('This is a member of the dictionary')
else:
    print('This is not a member of the dictionary')

This is not a member of the dictionary


In [ ]:
s="V"
s1=""
if s==s1:
  print(False)

In [ ]:
abc = {}
abc[1] = 1
abc['1'] = 2
abc[1] = abc[1] + 1
print(abc)

{1: 2, '1': 2}


In [ ]:
elements = (10, 20, 30, 40, 50, 60, 70, 80)
print(elements[2:5], elements[:4], elements[3:100])

(30, 40, 50) (10, 20, 30, 40) (40, 50, 60, 70, 80)


In [ ]:
name_lst = ["Vijay", "Vickey"]
tup = ("Item_1", 0.5, name_lst)
name_lst.append("Vishal")
print(tup)

('Item_1', 0.5, ['Vijay', 'Vickey', 'Vishal'])


In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
type(arr, dtype='float64')
print(arr)

In [7]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


In [8]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [9]:
a=[1,2],(1,2)
print(type(a))

<class 'tuple'>


In [1]:
import numpy as np
a = np.arange(10)
print(a[2:5])

[2 3 4]


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[-2])

6


In [1]:
import numpy as np
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [2]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0


In [3]:
import numpy as np
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12])
print((p + q)[1][1])

21


In [1]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [2]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A[:, ::-1])

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [3]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0